/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.53.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApplicationFormConfiguration : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationFormConfiguration {
    #[serde(rename = "adminRegistrationFormId", skip_serializing_if = "Option::is_none")]
    pub admin_registration_form_id: Option<uuid::Uuid>,
    #[serde(rename = "selfServiceFormConfiguration", skip_serializing_if = "Option::is_none")]
    pub self_service_form_configuration: Option<Box<models::SelfServiceFormConfiguration>>,
    #[serde(rename = "selfServiceFormId", skip_serializing_if = "Option::is_none")]
    pub self_service_form_id: Option<uuid::Uuid>,
}

impl ApplicationFormConfiguration {
    /// 
    pub fn new() -> ApplicationFormConfiguration {
        ApplicationFormConfiguration {
            admin_registration_form_id: None,
            self_service_form_configuration: None,
            self_service_form_id: None,
        }
    }
}

