/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.49.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// AuthenticatorAttachmentPreference : Describes the authenticator attachment modality preference for a WebAuthn workflow. See {@link AuthenticatorAttachment}
/// Describes the authenticator attachment modality preference for a WebAuthn workflow. See {@link AuthenticatorAttachment}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthenticatorAttachmentPreference {
    #[serde(rename = "any")]
    Any,
    #[serde(rename = "platform")]
    Platform,
    #[serde(rename = "crossPlatform")]
    CrossPlatform,

}

impl ToString for AuthenticatorAttachmentPreference {
    fn to_string(&self) -> String {
        match self {
            Self::Any => String::from("any"),
            Self::Platform => String::from("platform"),
            Self::CrossPlatform => String::from("crossPlatform"),
        }
    }
}

impl Default for AuthenticatorAttachmentPreference {
    fn default() -> AuthenticatorAttachmentPreference {
        Self::Any
    }
}

