/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.60.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthenticationThreats : 
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthenticationThreats {
    #[serde(rename = "ImpossibleTravel")]
    ImpossibleTravel,

}

impl std::fmt::Display for AuthenticationThreats {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ImpossibleTravel => write!(f, "ImpossibleTravel"),
        }
    }
}

impl Default for AuthenticationThreats {
    fn default() -> AuthenticationThreats {
        Self::ImpossibleTravel
    }
}

