/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.52.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BaseEventRequest : Base class for requests that can contain event information. This event information is used when sending Webhooks or emails  during the transaction. The caller is responsible for ensuring that the event information is correct.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseEventRequest {
    #[serde(rename = "eventInfo", skip_serializing_if = "Option::is_none")]
    pub event_info: Option<Box<models::EventInfo>>,
}

impl BaseEventRequest {
    /// Base class for requests that can contain event information. This event information is used when sending Webhooks or emails  during the transaction. The caller is responsible for ensuring that the event information is correct.
    pub fn new() -> BaseEventRequest {
        BaseEventRequest {
            event_info: None,
        }
    }
}

