/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.54.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChangePasswordReason : 
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChangePasswordReason {
    #[serde(rename = "Administrative")]
    Administrative,
    #[serde(rename = "Breached")]
    Breached,
    #[serde(rename = "Expired")]
    Expired,
    #[serde(rename = "Validation")]
    Validation,

}

impl std::fmt::Display for ChangePasswordReason {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Administrative => write!(f, "Administrative"),
            Self::Breached => write!(f, "Breached"),
            Self::Expired => write!(f, "Expired"),
            Self::Validation => write!(f, "Validation"),
        }
    }
}

impl Default for ChangePasswordReason {
    fn default() -> ChangePasswordReason {
        Self::Administrative
    }
}

