/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.52.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConnectorType : The types of connectors. This enum is stored as an ordinal on the <code>identities<code> table, order must be maintained.
/// The types of connectors. This enum is stored as an ordinal on the <code>identities<code> table, order must be maintained.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConnectorType {
    #[serde(rename = "FusionAuth")]
    FusionAuth,
    #[serde(rename = "Generic")]
    Generic,
    #[serde(rename = "LDAP")]
    Ldap,

}

impl std::fmt::Display for ConnectorType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FusionAuth => write!(f, "FusionAuth"),
            Self::Generic => write!(f, "Generic"),
            Self::Ldap => write!(f, "LDAP"),
        }
    }
}

impl Default for ConnectorType {
    fn default() -> ConnectorType {
        Self::FusionAuth
    }
}

