/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.49.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// CoseKeyType : COSE key type
/// COSE key type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CoseKeyType {
    #[serde(rename = "Reserved")]
    Reserved,
    #[serde(rename = "OKP")]
    Okp,
    #[serde(rename = "EC2")]
    Ec2,
    #[serde(rename = "RSA")]
    Rsa,
    #[serde(rename = "Symmetric")]
    Symmetric,

}

impl ToString for CoseKeyType {
    fn to_string(&self) -> String {
        match self {
            Self::Reserved => String::from("Reserved"),
            Self::Okp => String::from("OKP"),
            Self::Ec2 => String::from("EC2"),
            Self::Rsa => String::from("RSA"),
            Self::Symmetric => String::from("Symmetric"),
        }
    }
}

impl Default for CoseKeyType {
    fn default() -> CoseKeyType {
        Self::Reserved
    }
}

