/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.51.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DisplayableRawLogin : A displayable raw login that includes application name and user loginId.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisplayableRawLogin {
    #[serde(rename = "applicationName", skip_serializing_if = "Option::is_none")]
    pub application_name: Option<String>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Box<models::Location>>,
    #[serde(rename = "loginId", skip_serializing_if = "Option::is_none")]
    pub login_id: Option<String>,
}

impl DisplayableRawLogin {
    /// A displayable raw login that includes application name and user loginId.
    pub fn new() -> DisplayableRawLogin {
        DisplayableRawLogin {
            application_name: None,
            location: None,
            login_id: None,
        }
    }
}

