/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EmailTemplate : Stores an email template used to send emails to users.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailTemplate {
    #[serde(rename = "defaultFromName", skip_serializing_if = "Option::is_none")]
    pub default_from_name: Option<String>,
    #[serde(rename = "defaultHtmlTemplate", skip_serializing_if = "Option::is_none")]
    pub default_html_template: Option<String>,
    #[serde(rename = "defaultSubject", skip_serializing_if = "Option::is_none")]
    pub default_subject: Option<String>,
    #[serde(rename = "defaultTextTemplate", skip_serializing_if = "Option::is_none")]
    pub default_text_template: Option<String>,
    #[serde(rename = "fromEmail", skip_serializing_if = "Option::is_none")]
    pub from_email: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
    #[serde(rename = "insertInstant", skip_serializing_if = "Option::is_none")]
    pub insert_instant: Option<i64>,
    /// The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
    #[serde(rename = "lastUpdateInstant", skip_serializing_if = "Option::is_none")]
    pub last_update_instant: Option<i64>,
    /// Models a set of localized Strings that can be stored as JSON.
    #[serde(rename = "localizedFromNames", skip_serializing_if = "Option::is_none")]
    pub localized_from_names: Option<serde_json::Value>,
    /// Models a set of localized Strings that can be stored as JSON.
    #[serde(rename = "localizedHtmlTemplates", skip_serializing_if = "Option::is_none")]
    pub localized_html_templates: Option<serde_json::Value>,
    /// Models a set of localized Strings that can be stored as JSON.
    #[serde(rename = "localizedSubjects", skip_serializing_if = "Option::is_none")]
    pub localized_subjects: Option<serde_json::Value>,
    /// Models a set of localized Strings that can be stored as JSON.
    #[serde(rename = "localizedTextTemplates", skip_serializing_if = "Option::is_none")]
    pub localized_text_templates: Option<serde_json::Value>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl EmailTemplate {
    /// Stores an email template used to send emails to users.
    pub fn new() -> EmailTemplate {
        EmailTemplate {
            default_from_name: None,
            default_html_template: None,
            default_subject: None,
            default_text_template: None,
            from_email: None,
            id: None,
            insert_instant: None,
            last_update_instant: None,
            localized_from_names: None,
            localized_html_templates: None,
            localized_subjects: None,
            localized_text_templates: None,
            name: None,
        }
    }
}


