/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.53.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EmailTemplateRequest : Email template request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailTemplateRequest {
    #[serde(rename = "emailTemplate", skip_serializing_if = "Option::is_none")]
    pub email_template: Option<Box<models::EmailTemplate>>,
}

impl EmailTemplateRequest {
    /// Email template request.
    pub fn new() -> EmailTemplateRequest {
        EmailTemplateRequest {
            email_template: None,
        }
    }
}

