/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.50.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// EntityGrantResponse : Entity grant API response object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityGrantResponse {
    #[serde(rename = "grants", skip_serializing_if = "Option::is_none")]
    pub grants: Option<Vec<models::EntityGrant>>,
    #[serde(rename = "grant", skip_serializing_if = "Option::is_none")]
    pub grant: Option<Box<models::EntityGrant>>,
}

impl EntityGrantResponse {
    /// Entity grant API response object.
    pub fn new() -> EntityGrantResponse {
        EntityGrantResponse {
            grants: None,
            grant: None,
        }
    }
}

