/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.49.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// EntityTypeSearchRequest : Search request for entity types.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityTypeSearchRequest {
    #[serde(rename = "search", skip_serializing_if = "Option::is_none")]
    pub search: Option<Box<models::EntityTypeSearchCriteria>>,
}

impl EntityTypeSearchRequest {
    /// Search request for entity types.
    pub fn new() -> EntityTypeSearchRequest {
        EntityTypeSearchRequest {
            search: None,
        }
    }
}

