/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EventLogType : Event Log Type

/// Event Log Type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventLogType {
    #[serde(rename = "Information")]
    Information,
    #[serde(rename = "Debug")]
    Debug,
    #[serde(rename = "Error")]
    Error,

}

impl ToString for EventLogType {
    fn to_string(&self) -> String {
        match self {
            Self::Information => String::from("Information"),
            Self::Debug => String::from("Debug"),
            Self::Error => String::from("Error"),
        }
    }
}

impl Default for EventLogType {
    fn default() -> EventLogType {
        Self::Information
    }
}




