/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FamilyRequest : API request for managing families and members.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FamilyRequest {
    #[serde(rename = "familyMember", skip_serializing_if = "Option::is_none")]
    pub family_member: Option<Box<crate::models::FamilyMember>>,
}

impl FamilyRequest {
    /// API request for managing families and members.
    pub fn new() -> FamilyRequest {
        FamilyRequest {
            family_member: None,
        }
    }
}


