/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FormType : 

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FormType {
    #[serde(rename = "registration")]
    Registration,
    #[serde(rename = "adminRegistration")]
    AdminRegistration,
    #[serde(rename = "adminUser")]
    AdminUser,
    #[serde(rename = "selfServiceUser")]
    SelfServiceUser,

}

impl ToString for FormType {
    fn to_string(&self) -> String {
        match self {
            Self::Registration => String::from("registration"),
            Self::AdminRegistration => String::from("adminRegistration"),
            Self::AdminUser => String::from("adminUser"),
            Self::SelfServiceUser => String::from("selfServiceUser"),
        }
    }
}

impl Default for FormType {
    fn default() -> FormType {
        Self::Registration
    }
}




