/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.50.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// FormFieldAdminPolicy : 
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FormFieldAdminPolicy {
    #[serde(rename = "Edit")]
    Edit,
    #[serde(rename = "View")]
    View,

}

impl ToString for FormFieldAdminPolicy {
    fn to_string(&self) -> String {
        match self {
            Self::Edit => String::from("Edit"),
            Self::View => String::from("View"),
        }
    }
}

impl Default for FormFieldAdminPolicy {
    fn default() -> FormFieldAdminPolicy {
        Self::Edit
    }
}

