/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.49.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// GrantType : Authorization Grant types as defined by the <a href=\"https:tools.ietf.orghtmlrfc6749\">The OAuth 2.0 Authorization  Framework - RFC 6749<a>.  <p>  Specific names as defined by <a href=\"https:tools.ietf.orghtmlrfc7591#section-4.1\">  OAuth 2.0 Dynamic Client Registration Protocol - RFC 7591 Section 4.1<a>
/// Authorization Grant types as defined by the <a href=\"https:tools.ietf.orghtmlrfc6749\">The OAuth 2.0 Authorization  Framework - RFC 6749<a>.  <p>  Specific names as defined by <a href=\"https:tools.ietf.orghtmlrfc7591#section-4.1\">  OAuth 2.0 Dynamic Client Registration Protocol - RFC 7591 Section 4.1<a>
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GrantType {
    #[serde(rename = "authorization_code")]
    AuthorizationCode,
    #[serde(rename = "implicit")]
    Implicit,
    #[serde(rename = "password")]
    Password,
    #[serde(rename = "client_credentials")]
    ClientCredentials,
    #[serde(rename = "refresh_token")]
    RefreshToken,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "device_code")]
    DeviceCode,

}

impl ToString for GrantType {
    fn to_string(&self) -> String {
        match self {
            Self::AuthorizationCode => String::from("authorization_code"),
            Self::Implicit => String::from("implicit"),
            Self::Password => String::from("password"),
            Self::ClientCredentials => String::from("client_credentials"),
            Self::RefreshToken => String::from("refresh_token"),
            Self::Unknown => String::from("unknown"),
            Self::DeviceCode => String::from("device_code"),
        }
    }
}

impl Default for GrantType {
    fn default() -> GrantType {
        Self::AuthorizationCode
    }
}

