/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LambdaConfiguration {
    #[serde(rename = "accessTokenPopulateId", skip_serializing_if = "Option::is_none")]
    pub access_token_populate_id: Option<uuid::Uuid>,
    #[serde(rename = "idTokenPopulateId", skip_serializing_if = "Option::is_none")]
    pub id_token_populate_id: Option<uuid::Uuid>,
    #[serde(rename = "samlv2PopulateId", skip_serializing_if = "Option::is_none")]
    pub samlv2_populate_id: Option<uuid::Uuid>,
    #[serde(rename = "selfServiceRegistrationValidationId", skip_serializing_if = "Option::is_none")]
    pub self_service_registration_validation_id: Option<uuid::Uuid>,
}

impl LambdaConfiguration {
    pub fn new() -> LambdaConfiguration {
        LambdaConfiguration {
            access_token_populate_id: None,
            id_token_populate_id: None,
            samlv2_populate_id: None,
            self_service_registration_validation_id: None,
        }
    }
}


