/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.50.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// LoginRecordSearchResponse : A raw login record response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginRecordSearchResponse {
    #[serde(rename = "logins", skip_serializing_if = "Option::is_none")]
    pub logins: Option<Vec<models::DisplayableRawLogin>>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
}

impl LoginRecordSearchResponse {
    /// A raw login record response
    pub fn new() -> LoginRecordSearchResponse {
        LoginRecordSearchResponse {
            logins: None,
            total: None,
        }
    }
}

