/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.50.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// MemberRequest : Group Member Request
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MemberRequest {
    #[serde(rename = "members", skip_serializing_if = "Option::is_none")]
    pub members: Option<Vec<models::GroupMember>>,
}

impl MemberRequest {
    /// Group Member Request
    pub fn new() -> MemberRequest {
        MemberRequest {
            members: None,
        }
    }
}

