/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MessengerType : 

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MessengerType {
    #[serde(rename = "Generic")]
    Generic,
    #[serde(rename = "Kafka")]
    Kafka,
    #[serde(rename = "Twilio")]
    Twilio,

}

impl ToString for MessengerType {
    fn to_string(&self) -> String {
        match self {
            Self::Generic => String::from("Generic"),
            Self::Kafka => String::from("Kafka"),
            Self::Twilio => String::from("Twilio"),
        }
    }
}

impl Default for MessengerType {
    fn default() -> MessengerType {
        Self::Generic
    }
}




