/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PasswordValidationRulesResponse : 



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PasswordValidationRulesResponse {
    #[serde(rename = "passwordValidationRules", skip_serializing_if = "Option::is_none")]
    pub password_validation_rules: Option<Box<crate::models::PasswordValidationRules>>,
}

impl PasswordValidationRulesResponse {
    /// 
    pub fn new() -> PasswordValidationRulesResponse {
        PasswordValidationRulesResponse {
            password_validation_rules: None,
        }
    }
}


