/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PendingIdPLink : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PendingIdPLink {
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "identityProviderId", skip_serializing_if = "Option::is_none")]
    pub identity_provider_id: Option<uuid::Uuid>,
    #[serde(rename = "identityProviderLinks", skip_serializing_if = "Option::is_none")]
    pub identity_provider_links: Option<Vec<models::IdentityProviderLink>>,
    #[serde(rename = "identityProviderName", skip_serializing_if = "Option::is_none")]
    pub identity_provider_name: Option<String>,
    #[serde(rename = "identityProviderTenantConfiguration", skip_serializing_if = "Option::is_none")]
    pub identity_provider_tenant_configuration: Option<Box<models::IdentityProviderTenantConfiguration>>,
    #[serde(rename = "identityProviderType", skip_serializing_if = "Option::is_none")]
    pub identity_provider_type: Option<models::IdentityProviderType>,
    #[serde(rename = "identityProviderUserId", skip_serializing_if = "Option::is_none")]
    pub identity_provider_user_id: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::User>>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl PendingIdPLink {
    /// 
    pub fn new() -> PendingIdPLink {
        PendingIdPLink {
            display_name: None,
            email: None,
            identity_provider_id: None,
            identity_provider_links: None,
            identity_provider_name: None,
            identity_provider_tenant_configuration: None,
            identity_provider_type: None,
            identity_provider_user_id: None,
            user: None,
            username: None,
        }
    }
}

