/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.60.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PhoneUnverifiedOptions : Configuration for unverified phone number identities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PhoneUnverifiedOptions {
    #[serde(rename = "allowPhoneNumberChangeWhenGated", skip_serializing_if = "Option::is_none")]
    pub allow_phone_number_change_when_gated: Option<bool>,
    #[serde(rename = "behavior", skip_serializing_if = "Option::is_none")]
    pub behavior: Option<models::UnverifiedBehavior>,
}

impl PhoneUnverifiedOptions {
    /// Configuration for unverified phone number identities.
    pub fn new() -> PhoneUnverifiedOptions {
        PhoneUnverifiedOptions {
            allow_phone_number_change_when_gated: None,
            behavior: None,
        }
    }
}

