/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PreviewResponse : 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreviewResponse {
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<Box<crate::models::Email>>,
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Box<crate::models::Errors>>,
}

impl PreviewResponse {
    /// 
    pub fn new() -> PreviewResponse {
        PreviewResponse {
            email: None,
            errors: None,
        }
    }
}


