/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.57.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReactorMetrics : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReactorMetrics {
    #[serde(rename = "breachedPasswordMetrics", skip_serializing_if = "Option::is_none")]
    pub breached_password_metrics: Option<std::collections::HashMap<String, models::BreachedPasswordTenantMetric>>,
}

impl ReactorMetrics {
    /// 
    pub fn new() -> ReactorMetrics {
        ReactorMetrics {
            breached_password_metrics: None,
        }
    }
}

