/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ReactorFeatureStatus : 

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReactorFeatureStatus {
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "DISCONNECTED")]
    Disconnected,
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "DISABLED")]
    Disabled,
    #[serde(rename = "UNKNOWN")]
    Unknown,

}

impl ToString for ReactorFeatureStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Active => String::from("ACTIVE"),
            Self::Disconnected => String::from("DISCONNECTED"),
            Self::Pending => String::from("PENDING"),
            Self::Disabled => String::from("DISABLED"),
            Self::Unknown => String::from("UNKNOWN"),
        }
    }
}

impl Default for ReactorFeatureStatus {
    fn default() -> ReactorFeatureStatus {
        Self::Active
    }
}




