/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.52.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RefreshTokenExpirationPolicy : 
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RefreshTokenExpirationPolicy {
    #[serde(rename = "Fixed")]
    Fixed,
    #[serde(rename = "SlidingWindow")]
    SlidingWindow,
    #[serde(rename = "SlidingWindowWithMaximumLifetime")]
    SlidingWindowWithMaximumLifetime,

}

impl std::fmt::Display for RefreshTokenExpirationPolicy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Fixed => write!(f, "Fixed"),
            Self::SlidingWindow => write!(f, "SlidingWindow"),
            Self::SlidingWindowWithMaximumLifetime => write!(f, "SlidingWindowWithMaximumLifetime"),
        }
    }
}

impl Default for RefreshTokenExpirationPolicy {
    fn default() -> RefreshTokenExpirationPolicy {
        Self::Fixed
    }
}

