/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RefreshTokenResponse : API response for retrieving Refresh Tokens



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefreshTokenResponse {
    #[serde(rename = "refreshToken", skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<Box<crate::models::RefreshToken>>,
    #[serde(rename = "refreshTokens", skip_serializing_if = "Option::is_none")]
    pub refresh_tokens: Option<Vec<crate::models::RefreshToken>>,
}

impl RefreshTokenResponse {
    /// API response for retrieving Refresh Tokens
    pub fn new() -> RefreshTokenResponse {
        RefreshTokenResponse {
            refresh_token: None,
            refresh_tokens: None,
        }
    }
}


