/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.54.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RegistrationRequest : Registration API request object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegistrationRequest {
    #[serde(rename = "disableDomainBlock", skip_serializing_if = "Option::is_none")]
    pub disable_domain_block: Option<bool>,
    #[serde(rename = "generateAuthenticationToken", skip_serializing_if = "Option::is_none")]
    pub generate_authentication_token: Option<bool>,
    #[serde(rename = "registration", skip_serializing_if = "Option::is_none")]
    pub registration: Option<Box<models::UserRegistration>>,
    #[serde(rename = "sendSetPasswordEmail", skip_serializing_if = "Option::is_none")]
    pub send_set_password_email: Option<bool>,
    #[serde(rename = "skipRegistrationVerification", skip_serializing_if = "Option::is_none")]
    pub skip_registration_verification: Option<bool>,
    #[serde(rename = "skipVerification", skip_serializing_if = "Option::is_none")]
    pub skip_verification: Option<bool>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::User>>,
    #[serde(rename = "eventInfo", skip_serializing_if = "Option::is_none")]
    pub event_info: Option<Box<models::EventInfo>>,
}

impl RegistrationRequest {
    /// Registration API request object.
    pub fn new() -> RegistrationRequest {
        RegistrationRequest {
            disable_domain_block: None,
            generate_authentication_token: None,
            registration: None,
            send_set_password_email: None,
            skip_registration_verification: None,
            skip_verification: None,
            user: None,
            event_info: None,
        }
    }
}

