/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.50.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// Samlv2DestinationAssertionPolicy : 
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Samlv2DestinationAssertionPolicy {
    #[serde(rename = "Enabled")]
    Enabled,
    #[serde(rename = "Disabled")]
    Disabled,
    #[serde(rename = "AllowAlternates")]
    AllowAlternates,

}

impl ToString for Samlv2DestinationAssertionPolicy {
    fn to_string(&self) -> String {
        match self {
            Self::Enabled => String::from("Enabled"),
            Self::Disabled => String::from("Disabled"),
            Self::AllowAlternates => String::from("AllowAlternates"),
        }
    }
}

impl Default for Samlv2DestinationAssertionPolicy {
    fn default() -> Samlv2DestinationAssertionPolicy {
        Self::Enabled
    }
}

