/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.57.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Samlv2AssertionDecryptionConfiguration : Configuration for encrypted assertions when acting as SAML Service Provider
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Samlv2AssertionDecryptionConfiguration {
    #[serde(rename = "keyTransportDecryptionKeyId", skip_serializing_if = "Option::is_none")]
    pub key_transport_decryption_key_id: Option<uuid::Uuid>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl Samlv2AssertionDecryptionConfiguration {
    /// Configuration for encrypted assertions when acting as SAML Service Provider
    pub fn new() -> Samlv2AssertionDecryptionConfiguration {
        Samlv2AssertionDecryptionConfiguration {
            key_transport_decryption_key_id: None,
            enabled: None,
        }
    }
}

