/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.60.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SendSetPasswordIdentityType : Used to indicate which identity type a password \"request\" might go to. It could be  used for send set passwords or send password resets.
/// Used to indicate which identity type a password \"request\" might go to. It could be  used for send set passwords or send password resets.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SendSetPasswordIdentityType {
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "phone")]
    Phone,
    #[serde(rename = "doNotSend")]
    DoNotSend,

}

impl std::fmt::Display for SendSetPasswordIdentityType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Email => write!(f, "email"),
            Self::Phone => write!(f, "phone"),
            Self::DoNotSend => write!(f, "doNotSend"),
        }
    }
}

impl Default for SendSetPasswordIdentityType {
    fn default() -> SendSetPasswordIdentityType {
        Self::Email
    }
}

