/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.53.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SimpleThemeVariables : Theme object for values used in the css variables for simple themes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimpleThemeVariables {
    #[serde(rename = "alertBackgroundColor", skip_serializing_if = "Option::is_none")]
    pub alert_background_color: Option<String>,
    #[serde(rename = "alertFontColor", skip_serializing_if = "Option::is_none")]
    pub alert_font_color: Option<String>,
    #[serde(rename = "backgroundImageURL", skip_serializing_if = "Option::is_none")]
    pub background_image_url: Option<String>,
    #[serde(rename = "backgroundSize", skip_serializing_if = "Option::is_none")]
    pub background_size: Option<String>,
    #[serde(rename = "borderRadius", skip_serializing_if = "Option::is_none")]
    pub border_radius: Option<String>,
    #[serde(rename = "deleteButtonColor", skip_serializing_if = "Option::is_none")]
    pub delete_button_color: Option<String>,
    #[serde(rename = "deleteButtonFocusColor", skip_serializing_if = "Option::is_none")]
    pub delete_button_focus_color: Option<String>,
    #[serde(rename = "deleteButtonTextColor", skip_serializing_if = "Option::is_none")]
    pub delete_button_text_color: Option<String>,
    #[serde(rename = "deleteButtonTextFocusColor", skip_serializing_if = "Option::is_none")]
    pub delete_button_text_focus_color: Option<String>,
    #[serde(rename = "errorFontColor", skip_serializing_if = "Option::is_none")]
    pub error_font_color: Option<String>,
    #[serde(rename = "errorIconColor", skip_serializing_if = "Option::is_none")]
    pub error_icon_color: Option<String>,
    #[serde(rename = "fontColor", skip_serializing_if = "Option::is_none")]
    pub font_color: Option<String>,
    #[serde(rename = "fontFamily", skip_serializing_if = "Option::is_none")]
    pub font_family: Option<String>,
    #[serde(rename = "footerDisplay", skip_serializing_if = "Option::is_none")]
    pub footer_display: Option<bool>,
    #[serde(rename = "iconBackgroundColor", skip_serializing_if = "Option::is_none")]
    pub icon_background_color: Option<String>,
    #[serde(rename = "iconColor", skip_serializing_if = "Option::is_none")]
    pub icon_color: Option<String>,
    #[serde(rename = "infoIconColor", skip_serializing_if = "Option::is_none")]
    pub info_icon_color: Option<String>,
    #[serde(rename = "inputBackgroundColor", skip_serializing_if = "Option::is_none")]
    pub input_background_color: Option<String>,
    #[serde(rename = "inputIconColor", skip_serializing_if = "Option::is_none")]
    pub input_icon_color: Option<String>,
    #[serde(rename = "inputTextColor", skip_serializing_if = "Option::is_none")]
    pub input_text_color: Option<String>,
    #[serde(rename = "linkTextColor", skip_serializing_if = "Option::is_none")]
    pub link_text_color: Option<String>,
    #[serde(rename = "linkTextFocusColor", skip_serializing_if = "Option::is_none")]
    pub link_text_focus_color: Option<String>,
    #[serde(rename = "logoImageSize", skip_serializing_if = "Option::is_none")]
    pub logo_image_size: Option<String>,
    #[serde(rename = "logoImageURL", skip_serializing_if = "Option::is_none")]
    pub logo_image_url: Option<String>,
    #[serde(rename = "monoFontColor", skip_serializing_if = "Option::is_none")]
    pub mono_font_color: Option<String>,
    #[serde(rename = "monoFontFamily", skip_serializing_if = "Option::is_none")]
    pub mono_font_family: Option<String>,
    #[serde(rename = "pageBackgroundColor", skip_serializing_if = "Option::is_none")]
    pub page_background_color: Option<String>,
    #[serde(rename = "panelBackgroundColor", skip_serializing_if = "Option::is_none")]
    pub panel_background_color: Option<String>,
    #[serde(rename = "primaryButtonColor", skip_serializing_if = "Option::is_none")]
    pub primary_button_color: Option<String>,
    #[serde(rename = "primaryButtonFocusColor", skip_serializing_if = "Option::is_none")]
    pub primary_button_focus_color: Option<String>,
    #[serde(rename = "primaryButtonTextColor", skip_serializing_if = "Option::is_none")]
    pub primary_button_text_color: Option<String>,
    #[serde(rename = "primaryButtonTextFocusColor", skip_serializing_if = "Option::is_none")]
    pub primary_button_text_focus_color: Option<String>,
}

impl SimpleThemeVariables {
    /// Theme object for values used in the css variables for simple themes.
    pub fn new() -> SimpleThemeVariables {
        SimpleThemeVariables {
            alert_background_color: None,
            alert_font_color: None,
            background_image_url: None,
            background_size: None,
            border_radius: None,
            delete_button_color: None,
            delete_button_focus_color: None,
            delete_button_text_color: None,
            delete_button_text_focus_color: None,
            error_font_color: None,
            error_icon_color: None,
            font_color: None,
            font_family: None,
            footer_display: None,
            icon_background_color: None,
            icon_color: None,
            info_icon_color: None,
            input_background_color: None,
            input_icon_color: None,
            input_text_color: None,
            link_text_color: None,
            link_text_focus_color: None,
            logo_image_size: None,
            logo_image_url: None,
            mono_font_color: None,
            mono_font_family: None,
            page_background_color: None,
            panel_background_color: None,
            primary_button_color: None,
            primary_button_focus_color: None,
            primary_button_text_color: None,
            primary_button_text_focus_color: None,
        }
    }
}

