/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.60.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TenantLambdaConfiguration : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenantLambdaConfiguration {
    #[serde(rename = "loginValidationId", skip_serializing_if = "Option::is_none")]
    pub login_validation_id: Option<uuid::Uuid>,
    #[serde(rename = "scimEnterpriseUserRequestConverterId", skip_serializing_if = "Option::is_none")]
    pub scim_enterprise_user_request_converter_id: Option<uuid::Uuid>,
    #[serde(rename = "scimEnterpriseUserResponseConverterId", skip_serializing_if = "Option::is_none")]
    pub scim_enterprise_user_response_converter_id: Option<uuid::Uuid>,
    #[serde(rename = "scimGroupRequestConverterId", skip_serializing_if = "Option::is_none")]
    pub scim_group_request_converter_id: Option<uuid::Uuid>,
    #[serde(rename = "scimGroupResponseConverterId", skip_serializing_if = "Option::is_none")]
    pub scim_group_response_converter_id: Option<uuid::Uuid>,
    #[serde(rename = "scimUserRequestConverterId", skip_serializing_if = "Option::is_none")]
    pub scim_user_request_converter_id: Option<uuid::Uuid>,
    #[serde(rename = "scimUserResponseConverterId", skip_serializing_if = "Option::is_none")]
    pub scim_user_response_converter_id: Option<uuid::Uuid>,
}

impl TenantLambdaConfiguration {
    /// 
    pub fn new() -> TenantLambdaConfiguration {
        TenantLambdaConfiguration {
            login_validation_id: None,
            scim_enterprise_user_request_converter_id: None,
            scim_enterprise_user_response_converter_id: None,
            scim_group_request_converter_id: None,
            scim_group_response_converter_id: None,
            scim_user_request_converter_id: None,
            scim_user_response_converter_id: None,
        }
    }
}

