/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.49.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// TenantSearchResponse : Tenant search response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenantSearchResponse {
    #[serde(rename = "tenants", skip_serializing_if = "Option::is_none")]
    pub tenants: Option<Vec<models::Tenant>>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
}

impl TenantSearchResponse {
    /// Tenant search response
    pub fn new() -> TenantSearchResponse {
        TenantSearchResponse {
            tenants: None,
            total: None,
        }
    }
}

