/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.55.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TenantRequest : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenantRequest {
    #[serde(rename = "sourceTenantId", skip_serializing_if = "Option::is_none")]
    pub source_tenant_id: Option<uuid::Uuid>,
    #[serde(rename = "tenant", skip_serializing_if = "Option::is_none")]
    pub tenant: Option<Box<models::Tenant>>,
    #[serde(rename = "webhookIds", skip_serializing_if = "Option::is_none")]
    pub webhook_ids: Option<Vec<uuid::Uuid>>,
    #[serde(rename = "eventInfo", skip_serializing_if = "Option::is_none")]
    pub event_info: Option<Box<models::EventInfo>>,
}

impl TenantRequest {
    /// 
    pub fn new() -> TenantRequest {
        TenantRequest {
            source_tenant_id: None,
            tenant: None,
            webhook_ids: None,
            event_info: None,
        }
    }
}

