/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ThemeRequest : Theme API request object.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThemeRequest {
    #[serde(rename = "sourceThemeId", skip_serializing_if = "Option::is_none")]
    pub source_theme_id: Option<uuid::Uuid>,
    #[serde(rename = "theme", skip_serializing_if = "Option::is_none")]
    pub theme: Option<Box<crate::models::Theme>>,
}

impl ThemeRequest {
    /// Theme API request object.
    pub fn new() -> ThemeRequest {
        ThemeRequest {
            source_theme_id: None,
            theme: None,
        }
    }
}


