/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.57.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TotalsReportResponse : The response from the total report. This report stores the total numbers for each application.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TotalsReportResponse {
    #[serde(rename = "applicationTotals", skip_serializing_if = "Option::is_none")]
    pub application_totals: Option<std::collections::HashMap<String, models::Totals>>,
    #[serde(rename = "globalRegistrations", skip_serializing_if = "Option::is_none")]
    pub global_registrations: Option<i64>,
    #[serde(rename = "totalGlobalRegistrations", skip_serializing_if = "Option::is_none")]
    pub total_global_registrations: Option<i64>,
}

impl TotalsReportResponse {
    /// The response from the total report. This report stores the total numbers for each application.
    pub fn new() -> TotalsReportResponse {
        TotalsReportResponse {
            application_totals: None,
            global_registrations: None,
            total_global_registrations: None,
        }
    }
}

