/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.49.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransactionType : The transaction types for Webhooks and other event systems within FusionAuth.

/// The transaction types for Webhooks and other event systems within FusionAuth.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransactionType {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "Any")]
    Any,
    #[serde(rename = "SimpleMajority")]
    SimpleMajority,
    #[serde(rename = "SuperMajority")]
    SuperMajority,
    #[serde(rename = "AbsoluteMajority")]
    AbsoluteMajority,

}

impl ToString for TransactionType {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("None"),
            Self::Any => String::from("Any"),
            Self::SimpleMajority => String::from("SimpleMajority"),
            Self::SuperMajority => String::from("SuperMajority"),
            Self::AbsoluteMajority => String::from("AbsoluteMajority"),
        }
    }
}

impl Default for TransactionType {
    fn default() -> TransactionType {
        Self::None
    }
}




