/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.53.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UniqueUsernameStrategy {
    #[serde(rename = "Always")]
    Always,
    #[serde(rename = "OnCollision")]
    OnCollision,

}

impl std::fmt::Display for UniqueUsernameStrategy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Always => write!(f, "Always"),
            Self::OnCollision => write!(f, "OnCollision"),
        }
    }
}

impl Default for UniqueUsernameStrategy {
    fn default() -> UniqueUsernameStrategy {
        Self::Always
    }
}

