/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.50.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// UnknownScopePolicy : Policy for handling unknown OAuth scopes in the request
/// Policy for handling unknown OAuth scopes in the request
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UnknownScopePolicy {
    #[serde(rename = "Allow")]
    Allow,
    #[serde(rename = "Remove")]
    Remove,
    #[serde(rename = "Reject")]
    Reject,

}

impl ToString for UnknownScopePolicy {
    fn to_string(&self) -> String {
        match self {
            Self::Allow => String::from("Allow"),
            Self::Remove => String::from("Remove"),
            Self::Reject => String::from("Reject"),
        }
    }
}

impl Default for UnknownScopePolicy {
    fn default() -> UnknownScopePolicy {
        Self::Allow
    }
}

