/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.57.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnverifiedBehavior : 
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UnverifiedBehavior {
    #[serde(rename = "Allow")]
    Allow,
    #[serde(rename = "Gated")]
    Gated,

}

impl std::fmt::Display for UnverifiedBehavior {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Allow => write!(f, "Allow"),
            Self::Gated => write!(f, "Gated"),
        }
    }
}

impl Default for UnverifiedBehavior {
    fn default() -> UnverifiedBehavior {
        Self::Allow
    }
}

