/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.54.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserDeleteEvent : Models the User Event (and can be converted to JSON) that is used for all user modifications (create, update,  delete).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserDeleteEvent {
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::User>>,
}

impl UserDeleteEvent {
    /// Models the User Event (and can be converted to JSON) that is used for all user modifications (create, update,  delete).
    pub fn new() -> UserDeleteEvent {
        UserDeleteEvent {
            user: None,
        }
    }
}

