/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.60.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserCreateCompleteEvent : Models the User Created Event.  <p>  This is different than the user.create event in that it will be sent after the user has been created. This event cannot be made transactional.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCreateCompleteEvent {
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::User>>,
}

impl UserCreateCompleteEvent {
    /// Models the User Created Event.  <p>  This is different than the user.create event in that it will be sent after the user has been created. This event cannot be made transactional.
    pub fn new() -> UserCreateCompleteEvent {
        UserCreateCompleteEvent {
            user: None,
        }
    }
}

