/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.53.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebAuthnWorkflow : Identifies the WebAuthn workflow. This will affect the parameters used for credential creation  and request based on the Tenant configuration.
/// Identifies the WebAuthn workflow. This will affect the parameters used for credential creation  and request based on the Tenant configuration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WebAuthnWorkflow {
    #[serde(rename = "bootstrap")]
    Bootstrap,
    #[serde(rename = "general")]
    General,
    #[serde(rename = "reauthentication")]
    Reauthentication,

}

impl std::fmt::Display for WebAuthnWorkflow {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Bootstrap => write!(f, "bootstrap"),
            Self::General => write!(f, "general"),
            Self::Reauthentication => write!(f, "reauthentication"),
        }
    }
}

impl Default for WebAuthnWorkflow {
    fn default() -> WebAuthnWorkflow {
        Self::Bootstrap
    }
}

