/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.53.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookAttemptLogResponse : Webhook attempt log response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookAttemptLogResponse {
    #[serde(rename = "webhookAttemptLog", skip_serializing_if = "Option::is_none")]
    pub webhook_attempt_log: Option<Box<models::WebhookAttemptLog>>,
}

impl WebhookAttemptLogResponse {
    /// Webhook attempt log response.
    pub fn new() -> WebhookAttemptLogResponse {
        WebhookAttemptLogResponse {
            webhook_attempt_log: None,
        }
    }
}

