/*
 * FusionAuth API
 *
 * This is a FusionAuth server. Find out more at [https://fusionauth.io](https://fusionauth.io). You need to [set up an API key](https://fusionauth.io/docs/v1/tech/apis/authentication#managing-api-keys) in the FusionAuth instance you are using to test out the API calls.
 *
 * The version of the OpenAPI document: 1.50.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum XmlSignatureLocation {
    #[serde(rename = "Assertion")]
    Assertion,
    #[serde(rename = "Response")]
    Response,

}

impl ToString for XmlSignatureLocation {
    fn to_string(&self) -> String {
        match self {
            Self::Assertion => String::from("Assertion"),
            Self::Response => String::from("Response"),
        }
    }
}

impl Default for XmlSignatureLocation {
    fn default() -> XmlSignatureLocation {
        Self::Assertion
    }
}

