name: Create Issue on Version Change

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Script to Check Version and Create Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash ./notify.bash